# Generated by Django 4.1.2 on 2022-10-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='back_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
