# Generated by Django 4.1.2 on 2022-10-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='back_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
