# Generated by Django 4.1.2 on 2022-10-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_back', '0002_back_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('date', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
